version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  commands:
    - python -m pip install sphinx>=8.2.3 furo>=2025.9.25 sphinx_design>=0.6.1
    - python -m sphinx -aEnTW --builder html --keep-going docs/ $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true