version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  commands:
    - python -m pip install sphinx>=9.0.4 furo>=2025.12.19 sphinx_design>=0.6.1 sphinxext-opengraph[social-cards]>=0.13.0
    - python -m sphinx -aEnTW --builder html --keep-going docs/ $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true