{
 "title": "Catherine-Chan Metrics",
 "description": "The Metrics Dashboard for Catherine-Chan",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Static Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected?",
   "type": "stat",
   "description": "Is Catherine-Chan connected to Discord?",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_connected{job=\"catherine\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Process Started Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{instance=\"localhost:6789\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"catherine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Commands",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_stat_app_total_commands{job=\"catherine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catherine-Chan Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version_info_info{job=\"catherine\"}",
     "legendFormat": "{{build_version}}"
    }
   ]
  },
  {
   "title": "discord.py version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version_info_info{job=\"catherine\"}",
     "legendFormat": "{{dpy_version}}"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version_info_info{job=\"catherine\"}",
     "legendFormat": "{{python_version}}"
    }
   ]
  },
  { "title": "Memory and GC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Current Resident Memory Usage",
   "type": "timeseries",
   "description": "Basically the current memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"catherine\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Objects Collected",
   "type": "timeseries",
   "description": "Python GC Objects Collected - Useful to track current objects",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=\"0\"}",
     "legendFormat": "Gen 1"
    },
    {
     "expr": "python_gc_objects_collected_total{generation=\"1\"}",
     "legendFormat": "Gen 2"
    },
    {
     "expr": "python_gc_objects_collected_total{generation=\"2\"}",
     "legendFormat": "Gen 3"
    },
    {
     "expr": "sum(python_gc_objects_collected_total{generation=\"0\"}) + sum(python_gc_objects_collected_total{generation=\"1\"}) + sum(python_gc_objects_collected_total{generation=\"2\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Discord and Slash Invocations Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Ping to Discord",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "discord_latency{shard=\"None\"} * 1000",
     "legendFormat": "Discord Ping"
    }
   ]
  },
  {
   "title": "Slash Commands Invoked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_on_app_command_total{job=\"catherine\"}",
     "legendFormat": "Commands Invoked"
    }
   ]
  },
  {
   "title": "Guild, Member and Channel Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Total Guilds",
   "type": "timeseries",
   "description": "Total guilds that can be seen",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_stat_total_guilds{job=\"catherine\"}",
     "legendFormat": "Total Guilds"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "timeseries",
   "description": "Total channels that Catherine-Chan can see",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_stat_total_text_channels{job=\"catherine\"}",
     "legendFormat": "Text Channels"
    },
    {
     "expr": "discord_stat_total_voice_channels{job=\"catherine\"}",
     "legendFormat": "Voice Channels"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "timeseries",
   "description": "The total users that Catherine-Chan can see. Both unique and total users",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_stat_total_unique_users{job=\"catherine\"}",
     "legendFormat": "Total Unique Users"
    },
    {
     "expr": "discord_stat_total_users{job=\"catherine\"}",
     "legendFormat": "Total Users"
    }
   ]
  },
  { "title": "Blacklist Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Attempted Commands (Blacklist)",
   "type": "timeseries",
   "description": "Amount of blacklisted users trying to run commands",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_attempted_commands_total{job=\"catherine\"}",
     "legendFormat": "Attempted Commands"
    }
   ]
  },
  {
   "title": "Blacklisted Users",
   "type": "timeseries",
   "description": "The amount of users blacklisted from using Catherine-Chan",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "discord_blacklisted_users{job=\"catherine\"}",
     "legendFormat": "Users"
    }
   ]
  },
  { "title": "Feature Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Successful Pronouns Tester Runs",
   "type": "timeseries",
   "description": "The amount of successful pronouns tester runs made. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "discord_pronouns_tester_total{job=\"catherine\"}",
     "legendFormat": "Successful Runs"
    }
   ]
  }
 ]
}