ignore:
  - "bot/libs/ui/**"
  - "bot/libs/utils/pages/**"
  - "bot/libs/utils/logger.py"
  - "bot/libs/utils/time.py"
  - "bot/libs/utils/tree.py" # How can you unit test a CommandTree...
  - "bot/libs/utils/view.py" # Also how can you unit test a View...
  - "bot/libs/utils/modal.py" # Can't test a modal
  # Although one coro is tested, the another can't be tested. We need to look up the blacklist cache which is held on the bot.
  # So basically we will just have to ignore this one.
  - "bot/libs/utils/blacklist.py"
  - "bot/libs/cog_utils/prometheus_metrics/**" # There is simply no way to test for stuff like Gauges, etc.
  - "bot/cogs/**"
  - "bot/catherinecore.py"
  - "bot/catherinebot.py"
