version: "3.9"
name: "catherine-dev"
services:
  postgres:
    container_name: Catherine-Postgres-Dev
    image: catherine-pg:dev-latest
    build:
      context: ./docker/pg
      dockerfile: Dockerfile
    env_file:
      - bot/.env
    volumes:
      - dev_postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dev_postgres_volume:
